config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'greeter/hello'
  get 'greeter/goodbye' => "greeter#goodbye"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coursera.rb
class Coursera
	include HTTParty

		base_uri 'https://www.googleapis.com/books/v1/volumes'
		default_params q: "isbn:0747532699"
		format :json

	def self.for term
		get("", query: {})["items"]
	end
end

pp Coursera.for "python"

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  	@search_term = "jhu"
  	@courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  	random_names = ["Alex", "Adam", "Greta"]
  	@name = random_names.sample
  	@time = Time.now
  	@time_displayed ||= 0
  	@time_displayed += 1
  	
  end

  def goodbye
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
	def formatted_time(time)
		time.strftime("%I:%M%p")
	end

end

app/views/courses/index.html.erb
<h1>Courses</h1>
<% @courses.each do |course| %>
	<p> Book  <%= course["kind"] %> </p>
<% end%>

app/views/greeter/goodbye.html.erb
<% random_names = ["Alex", "Adam", "Greta"] %>
<h1>Good Bye , <%= random_names.sample %></h1>
<p>The time now is <%= Time.now %></p>

app/views/greeter/hello.html.erb
<h1>Greetings , <%= @name %></h1>
<p>The time now is <%= formatted_time(@time) %></p>
<p> ..... <%= @time_displayed %></p>
<p>	<%= link_to "Google", "https://www.google.com" %></p>
<p>	<%= link_to "Goodbye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>